# -*- coding: utf-8 -*-
"""task-4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cptje8Rk1T7DQPqJbVdDj6VIk1otC-8d
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

# Load dataset
df = pd.read_csv("insurance.csv")

print("Shape:", df.shape)
print("Columns:", df.columns)
print(df.head())

# Check missing values
print("\nMissing Values:\n", df.isnull().sum())

# EDA Visualizations
plt.figure(figsize=(8,5))
sns.scatterplot(x="age", y="charges", data=df)
plt.title("Age vs Insurance Charges")
plt.show()

plt.figure(figsize=(8,5))
sns.scatterplot(x="bmi", y="charges", data=df)
plt.title("BMI vs Insurance Charges")
plt.show()

plt.figure(figsize=(6,4))
sns.boxplot(x="smoker", y="charges", data=df)
plt.title("Smoker vs Insurance Charges")
plt.show()

# Encoding categorical variables
df = pd.get_dummies(df, drop_first=True)

# Split features and target
X = df.drop("charges", axis=1)
y = df["charges"]

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Train Linear Regression model
model = LinearRegression()
model.fit(X_train, y_train)

# Prediction
y_pred = model.predict(X_test)

# Evaluation
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print("\nMAE:", mae)
print("RMSE:", rmse)

# Actual vs Predicted graph
plt.figure(figsize=(8,5))
plt.scatter(y_test, y_pred)
plt.title("Actual vs Predicted Charges")
plt.xlabel("Actual Charges")
plt.ylabel("Predicted Charges")
plt.show()