# -*- coding: utf-8 -*-
"""Task1_Iris_Visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P5zTwsHYC-DfeODehBOQvGigvzo-wATh
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load dataset
df = sns.load_dataset("iris")

# Dataset structure
print("Shape:", df.shape)
print("Columns:", df.columns)
print("\nFirst 5 rows:")
print(df.head())

# Dataset summary
print("\nDataset Info:")
print(df.info())

print("\nDataset Description:")
print(df.describe())

# Missing values check
print("\nMissing Values:")
print(df.isnull().sum())

# Scatter Plot
plt.figure(figsize=(8,5))
sns.scatterplot(x="petal_length", y="petal_width", hue="species", data=df)
plt.title("Scatter Plot: Petal Length vs Petal Width")
plt.show()

# Histogram
plt.figure(figsize=(8,5))
plt.hist(df["sepal_length"], bins=20, edgecolor="black")
plt.title("Histogram of Sepal Length")
plt.xlabel("Sepal Length")
plt.ylabel("Frequency")
plt.show()

# Box Plot
plt.figure(figsize=(8,5))
sns.boxplot(x="species", y="petal_width", data=df)
plt.title("Box Plot: Petal Width by Species")
plt.show()

sns.pairplot(df, hue="species")
plt.show()

