# -*- coding: utf-8 -*-
"""task-5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UvKV0Eu6p3t2Ya8IOcizIWvFb3cZAsGy
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

# Load dataset
df = pd.read_csv("bank.csv", sep=",")   # change filename if bank-full.csv
print("Shape:", df.shape)
print(df.head())

# Basic EDA
plt.figure(figsize=(8,5))
sns.histplot(df["age"], bins=30, kde=True)
plt.title("Age Distribution")
plt.show()

plt.figure(figsize=(10,5))
sns.countplot(x="job", hue="deposit", data=df)
plt.title("Job vs Loan Acceptance")
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(6,4))
sns.countplot(x="marital", hue="deposit", data=df)
plt.title("Marital Status vs Loan Acceptance")
plt.show()

# Encoding
le = LabelEncoder()
for col in df.columns:
    if df[col].dtype == "object":
        df[col] = le.fit_transform(df[col])

# Split features and target
X = df.drop("deposit", axis=1)
y = df["deposit"]

# Train test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Scale numerical features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Logistic Regression model
model = LogisticRegression(max_iter=1000)
model.fit(X_train_scaled, y_train)

# Prediction
y_pred = model.predict(X_test_scaled)

# Evaluation
print("Logistic Regression Accuracy:", accuracy_score(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

plt.figure(figsize=(5,4))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
plt.title("Confusion Matrix - Logistic Regression")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

print("\nClassification Report:\n", classification_report(y_test, y_pred))

# Decision Tree model (optional)
tree = DecisionTreeClassifier(random_state=42)
tree.fit(X_train, y_train)

tree_pred = tree.predict(X_test)
print("Decision Tree Accuracy:", accuracy_score(y_test, tree_pred))

# Business Insights (Acceptance Rates)
df_original = pd.read_csv("bank.csv", sep=",")

print("\nAcceptance Rate by Job:\n")
print(df_original.groupby("job")["deposit"].value_counts(normalize=True).unstack())

print("\nAcceptance Rate by Marital Status:\n")
print(df_original.groupby("marital")["deposit"].value_counts(normalize=True).unstack())

